import Head from "next/head";
import ContactSection from "../components/ContactSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import PortfolioSection from "../components/PortfolioSection";
import ServicesSection from "../components/ServicesSection";
import { useEffect } from "react";
import axios from "axios";
export default function Home() {
  // useEffect(() => {
  //   axios
  //     .post("http://localhost:3000/api/contact", {
  //       email: "rayhanbd7075@gmail.com",
  //     })
  //     .then((res) => {
  //       alert("Send Mail To You");
  //     })
  //     .catch((e) => console.log(e));
  // }, []);

  return (
    <>
      <Head>
        <title>Meelad Samadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <HeroSection />
      <ServicesSection />
      <PortfolioSection />
      <ContactSection />
      <Footer />
    </>
  );
}
